
export const MEDICINE_CREATE_REQUEST="MEDICINE_CREATE_REQUEST";
export const MEDICINE_CREATE_SUCCESS="MEDICINE_CREATE_SUCCESS";
export const MEDICINE_CREATE_FAILED="MEDICINE_CREATE_FAILED";

export const MEDICINE_READ_REQUEST="MEDICINE_READ_REQUEST";
export const MEDICINE_READ_SUCCESS="MEDICINE_READ_SUCCESS";
export const MEDICINE_READ_FAILED="MEDICINE_READ_FAILED";

export const SPECIFIC_MEDICINE_READ_REQUEST="SPECIFIC_MEDICINE_READ_REQUEST";
export const SPECIFIC_MEDICINE_READ_SUCCESS="SPECIFIC_MEDICINE_READ_SUCCESS";
export const SPECIFIC_MEDICINE_READ_FAILED="SPECIFIC_MEDICINE_READ_FAILED";

export const MEDICINE_UPDATE_REQUEST="MEDICINE_UPDATE_REQUEST";
export const MEDICINE_UPDATE_SUCCESS="MEDICINE_UPDATE_SUCCESS";
export const MEDICINE_UPDATE_FAILED="MEDICINE_UPDATE_FAILED";


