export const ORDER_CREATE_REQUEST="ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS="ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAILED="ORDER_CREATE_FAILED";

export const ORDER_CANCEL_REQUEST="ORDER_CANCEL_REQUEST";
export const ORDER_CANCEL_SUCCESS="ORDER_CANCEL_SUCCESS";
export const ORDER_CANCEL_FAILED="ORDER_CANCEL_FAILED";

export const ALL_ORDER_READ_REQUEST="ALL_ORDER_READ_REQUEST";
export const ALL_ORDER_READ_SUCCESS="ALL_ORDER_READ_SUCCESS";
export const ALL_ORDER_READ_FAILED="ALL_ORDER_READ_FAILED";


export const ORDER_READ_REQUEST="ORDER_READ_REQUEST";
export const ORDER_READ_SUCCESS="ORDER_READ_SUCCESS";
export const ORDER_READ_FAILED="ORDER_READ_FAILED";
