export const ORDER_CREATE_REQUEST="ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS="ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAILED="ORDER_CREATE_FAILED";

export const ORDER_UPDATE_REQUEST="ORDER_UPDATE_REQUEST";
export const ORDER_UPDATE_SUCCESS="ORDER_UPDATE_SUCCESS";
export const ORDER_UPDATE_FAILED="ORDER_UPDATE_FAILED";

export const ALL_ORDER_READ_REQUEST="ALL_ORDER_READ_REQUEST";
export const ALL_ORDER_READ_SUCCESS="ALL_ORDER_READ_SUCCESS";
export const ALL_ORDER_READ_FAILED="ALL_ORDER_READ_FAILED";


export const ORDER_READ_REQUEST="ORDER_READ_REQUEST";
export const ORDER_READ_SUCCESS="ORDER_READ_SUCCESS";
export const ORDER_READ_FAILED="ORDER_READ_FAILED";
